spring.application.name=ElectricityBillSystem

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/Electricity
spring.datasource.username=root
spring.datasource.password=G@yuR@m05

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=false
